#@ namespaces = [
#@   "ns01",
#@ ]

---
apiVersion: v1
kind: Namespace
metadata:
  name: bingo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bingo
  namespace: bingo

#@ for ns in namespaces:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bingo
  namespace: #@ ns
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["run.tanzu.vmware.com"]
  resources: ["tanzukubernetesclusters"]
  verbs: ["create","update","get","list","delete","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bingo
  namespace: #@ ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bingo
subjects:
- kind: ServiceAccount
  name: bingo
  namespace: bingo
#@ end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingo
  namespace: bingo
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: bingo
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: bingo
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.1
        command:
        - /git-sync
        - -v=100
        - --ssh
        - --ssh-known-hosts=false
        - --ssh-known-hosts-file=/dev/null
        env:
        - name: GIT_SYNC_REPO
          valueFrom:
            configMapKeyRef: { name: bingo-config, key: repo }
        - name: GIT_SYNC_BRANCH
          valueFrom:
            configMapKeyRef: { name: bingo-config, key: branch }
        - name: GIT_SYNC_REV
          valueFrom:
            configMapKeyRef: { name: bingo-config, key: rev }
        volumeMounts:
        - name: creds
          mountPath: /etc/git-secret/ssh
          readOnly: true
          subPath: ssh-key
      volumes:
      - name: creds
        secret:
          secretName: bingo-creds
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bingo-config
  namespace: bingo
data:
  repo: git@github.com:hoegaarden/bingo
  branch: main
  rev: HEAD
---
#! apiVersion: v1
#! kind: Secret
#! metadata:
#!   name: bingo-creds
#!   namespace: bingo
#! stringData:
#!   ssh-key: |
#!     -----BEGIN OPENSSH PRIVATE KEY-----
#!     b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
#!       [...]
#!     Nonha/zPwQDL8AAAALaG9ybGhAYmx1cHA=
#!     -----END OPENSSH PRIVATE KEY-----
