#@ load("@ytt:data", "data")

#@ cfg = data.values["cert-manager"]

#@ if cfg.enabled:
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  annotations:
    kapp.k14s.io/change-group: cert-manager/main
    kapp.k14s.io/change-rule.0: upsert after upserting base/ns
    kapp.k14s.io/change-rule.1: delete before deleting base/ns
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: #@ cfg.version
#@ end
